[theme]
primaryColor = "#00bfff"          # Color de acento (Azul cielo)
backgroundColor = "#0e1117"       # Fondo principal (Gris oscuro)
secondaryBackgroundColor = "#1f2937" # Fondo de la barra lateral y tarjetas
textColor = "#ffffff"             # Color del texto principal (Blanco)
font = "sans serif"
