# ======================
# CONFIG INFLUXDB
# ======================
#INFLUX_HOST = "localhost"
#INFLUX_PORT = 8086
#INFLUX_DB = "albuferaws_db"
INFLUX_URL = "https://eu-central-1-1.aws.cloud2.influxdata.com/"
INFLUX_TOKEN = "hg475TtMSOO4U7dQVWIbijmK-1JFpfbhxUtmuS6QS4v-H3xNZ21k6XnEukiTVfzGNF4GZBVRvpvlR0cEqAofKg=="
INFLUX_ORG = "UPV"
INFLUX_BUCKET = "albuferaws"
